COL1 = 64
COL2 = 192
COL3 = 320
COL4 = 448
SPRITE = "px.png"
SB_DIR = "sb/"
SPRITE_FILE = f"{SB_DIR}{SPRITE}"
HEADER = "[Events]\n"
FOOTER = "// Generated by Erkfir's 2[4K] Storyboard converter"

MAGIC = 13720 # Literal magic number
RAW_SCROLL = 20
SCROLL = 480 / (MAGIC / RAW_SCROLL)
